[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+simd128",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--max-memory=2147483648",
    "-C", "link-arg=--no-entry",
    "-C", "link-arg=--export-dynamic",
]

[unstable]
build-std = ["core", "alloc"]
